### PR TITLE
.NET 9.0 locking fixes

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Fixes locking issues in .NET 9.0. You should not use System.Threading.Lock in conjunction with Monitor since the .NET 9.0 version is not Monitor-based.

### CODE REVIEW

**Comment by alexyakunin** [comment]
Wow, sorry, I somehow just noticed this.

**Comment by alexyakunin** [comment]
I did some work on this already, so I'll merge what's possible to merge.

**Comment by alexyakunin** [comment]
Hi, sorry, I can't merge this - mostly because I already did the same set of changes, though keeping them compatible with the older versions of .NET:
image

But... I am really sorry I didn't spot this PR on time. I'd be absolutely happy to see more contribs like this - please don't hesitate to reach me out anywhere in case you add another PR, e.g. on Actual Chat: https://actual.chat/u/hjp639qb6bp1 , I promise to review it quickly.

**Comment by MarkCiliaVincenti** [comment]
@alexyakunin if you're interested I can redo this PR. It will result in cleaner code.

**Pull request closed without merging**
